export type SiteConfig = typeof siteConfig

export const siteConfig = {
  name: "Eyal Cohen",
  description:
    "Beautifully designed components built with Radix UI and Tailwind CSS.",
  mainNav: [
    {
      title: "Home",
      href: "/",
    },
    {
      title: "About",
      href: "/about",
    },
    {
      title: "Newsletter",
      href: "https://eyalcohen.substack.com/",
    },
    {
      title: "Blog",
      href: "/blog",
    },
    {
      title: "Curation",
      href: "/curation",
    },
  ],
  posts: [
    {
      title: "Why Does Next.js Is Re-Rendering the Whole Page On Route Change",
      description: "A common problem with Next.js and how to solve it",
      slug: "why-nextjs-is-rerendering",
    },
    {
      title: "Building a Serverless Job Board with Next.js and Contentful",
      description: "Learn how to build a job board",
      slug: "nextjs-contentful-job-board",
    },
    {
      title: "Creating a Media Object with TailwindCSS",
      description: "Useful CSS pattern",
      slug: "media-objects-with-tailwind",
    },
    {
      title: "How To Play Video With React Native And Expo",
      description: "A step by step guide to video in React Native using Expo.",
      slug: "how-to-play-video-with-react-native-and-expo",
    },
    {
      title: "How To Find If Software Development Is For You",
      description:
        "I'll try to help you understand if software development is for you.",
      slug: "is-software-development-for-you",
    },
  ],
  projects: [
    {
      title: "Desert Lion",
      description: "A time travel debugger and monitoring tool for the web",
      href: "https://desertlion.io",
    },
    {
      title: "FrontWork",
      description: "A front-end development marketplace",
      href: "https://frontwork.dev",
    },
    {
      title: "Kvozut",
      description:
        "Website for students in my university to find and share groups, files, reviews, and more",
      href: "https://kvozut.co.il",
    },
    {
      title: "Zero to App: The Complete React Native Book In Hebrew",
      description: "A hebrew guide for React Native beginners",
      href: "https://coheneyal.gumroad.com/l/zero-to-app-react-native",
    },
  ],
  experience: [
    {
      title: "Founder, CEO",
      date: "2022 - 2023",
      link: "https://desertlion.io",
      name: "Desert Lion",
      location: "Tel Aviv",
      tags: [
        "React",
        "Next.js",
        "TypeScript",
        "Python",
        "AWS",
        "Glue",
        "SageMaker",
        "NLP",
        "Deep Learning",
        "Redis",
        "Puppeteer",
        "Prisma",
        "Postgres",
      ],
    },
    {
      title: "Front-End Experts Community Lead",
      date: "2023",
      link: "https://a.team",
      name: "A.Team",
      location: "Remote",
      tags: ["DevRel", "Community Lead"],
    },
    {
      title: "Software Consultant",
      date: "2021 - 2023",
      link: "https://getbonfire.xyz",
      name: "Bonfire",
      location: "Remote",
      tags: [
        "React",
        "Next.js",
        "Apollo",
        "Graphql",
        "Prisma",
        "AWS",
        "Postgres",
        "TypeScript",
      ],
    },
    {
      title: "Front End Consultant",
      date: "2021",
      link: "https://lovestoriestv.com",
      name: "LoveStoriesTV",
      location: "Remote",
      tags: ["React", "Redux"],
    },
    {
      title: "Software Consultant",
      date: "2020",
      link: "https://getbalance.com",
      name: "Balance",
      location: "Tel Aviv",
      tags: [
        "AWS",
        "Node.js",
        "NestJS",
        "React",
        "Mobx",
        "Postgres",
        "Kubernetes",
        "TypeScript",
      ],
    },
    {
      title: "Software Engineer",
      date: "2019",
      link: "https://ironsrc.com",
      name: "ironSource",
      location: "Tel Aviv",
      tags: [
        "AWS",
        "Node.js",
        "Express",
        "React",
        "React Native",
        "Mobx",
        "MemSQL",
        "MySQL",
        "MongoDB",
        "Vue",
        "Docker",
        "TypeScript",
      ],
    },
    {
      title: "Software Engineer",
      date: "2017 - 2019",
      link: "https://myplay.com",
      name: "MyPlay",
      location: "Netanya",
      tags: [
        "Node.js",
        "Express",
        "React",
        "React Native",
        "Redux",
        "Mobx",
        "MongoDB",
        "C++",
        "Docker",
        "OpenCV",
        "TypeScript",
      ],
    },
    {
      title: "Full Stack Developer",
      date: "2016 - 2017",
      name: "DevSense",
      location: "Haifa",
      tags: [
        "AngularJS",
        "Node.js",
        "Express",
        "React",
        "React Native",
        "Redux",
        "Vue",
        "PHP",
        "Laravel",
        "MongoDB",
        "MySQL",
        "Python",
      ],
    },
  ],
  links: {
    twitter: "https://twitter.com/",
    github: "https://github.com/eyalcohen4",
    linkedin: "https://www.linkedin.com/in/eyalcohen",
    stackoverflow: "https://www.linkedin.com/in/eyalcohen",
  },
}
